### PR TITLE
Skip children of blocks with unsupported type

### LINKED ISSUE #30: Bug: Fetching block children on unsupported block types result in pipeline stopping
### Bug description

Attempting to fetch the block children of a block that has an `unsupported` block type
```
node 3209bd37-63b3-4b2b-aa37-e7380ce3e48c stopped with error: error reading from source: read plugin error: failed fetching content for d6cb66d3-2b2d-4243-8490-6d100ca127af: failed getting children for block ID bbb41355-fb03-4da4-baa5-dc9e54319b62, cursor : Block type link_to_page is not supported via the API.
```

### Steps to reproduce

1. Generate a 1:1 Template document on Notion
2. Share that document with an internal integration
3. Create a conduit pipeline, with a Notion source connector
4. Observe the source notion connector logs. You will see a log with a similar error: 
```
node 3209bd37-63b3-4b2b-aa37-e7380ce3e48c stopped with error: error reading from source: read plugin error: failed fetching content for d6cb66d3-2b2d-4243-8490-6d100ca127af: failed getting children for block ID bbb41355-fb03-4da4-baa5-dc9e54319b62, cursor : Block type link_to_page is not supported via the API.
```

### Version

v0.2.0 Linux_x86_64

### PR DESCRIPTION
**Pull request by samirketema**
### Description

Prevents the attempt to fetch children of blocks with the `unsupported` type. 
Fixes #30 

** Testing still in-progress**

### Quick checks:

- [x] There is no other [pull request](https://github.com/conduitio-labs/conduit-connector-notion/pulls) for the same update/change.
- [ ] I have written unit tests.
- [ ] I have made sure that the PR is of reasonable size and can be easily reviewed.

### CODE REVIEW

File: source.go [hunk 1]
```diff
@@ -171,23 +189,32 @@ func (s *Source) nextPage(ctx context.Context) (sdk.Record, error) {
...
-func (s *Source) getChildren(ctx context.Context, blockID string) ([]notion.Block, error) {
+func (s *Source) getChildren(ctx context.Context, block notion.Block) ([]notion.Block, error) {
+	if block.GetType() == notion.BlockTypeUnsupported {
+		// skip children of unsupported block types
+		sdk.Logger(ctx).Warn().
+			Str("block_type", block.GetType().String()).
+			Str("block_id", block.GetID().String()).
+			Msg("skipping children of unsupported block")
+		return []notion.Block{}, nil
+	}
```
Comment (hariso) [inline source.go:200]: IIUC, we want to skip children of a block that is of `unsupported` type, but we still want the block itself?

Comment (samirketema) [reply source.go:200]: @hariso yup! In this case, I used the default `Brainstorm` template from Notion. The `unsupported` block type came from the block to add a new template in the screenshot below in `Add a New Topic`. The plaintext from that block may still be relevant, where the child of the block should not be iterated on.
Screenshot 2023-01-04 at 8 28 59 AM

**Review by hariso — APPROVED** [review]
:rocket:
